// Package manifest loads the immutable launcher configuration generated by Nix.
package manifest

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const version = 1

// Manifest is the versioned boundary between the Nix package and the launcher.
type Manifest struct {
	Version               int             `json:"version"`
	Platform              string          `json:"platform"`
	FenceExecutable       string          `json:"fenceExecutable"`
	RepoWolfClientDir     string          `json:"repoWolfClientDir"`
	BasePolicy            string          `json:"basePolicy"`
	ClosurePathsFile      string          `json:"closurePathsFile"`
	ScratchRoot           string          `json:"scratchRoot"`
	ACLProbe              []string        `json:"aclProbe"`
	ProtectedPathPatterns []string        `json:"protectedPathPatterns"`
	PathEntries           []string        `json:"pathEntries"`
	ExplicitConfigDir     *string         `json:"explicitConfigDir"`
	Agent                 Agent           `json:"agent"`
	Docker                ContainerConfig `json:"docker"`
	Podman                ContainerConfig `json:"podman"`
}

// Agent describes the immutable program the launcher starts.
type Agent struct {
	Name              string   `json:"name"`
	Executable        string   `json:"executable"`
	MandatoryArgs     []string `json:"mandatoryArgs"`
	ReservedFlags     []string `json:"reservedFlags"`
	ConfigEnvironment string   `json:"configEnvironment"`
	DefaultStatePaths []string `json:"defaultStatePaths"`
	DarwinSettings    string   `json:"darwinSettings,omitempty"`
}

// ContainerConfig describes one optional container client integration.
type ContainerConfig struct {
	Enable         bool     `json:"enable"`
	SocketPath     *string  `json:"socketPath"`
	HostPorts      []uint16 `json:"hostPorts"`
	ClientPrograms []string `json:"clientPrograms"`
}

// Load reads and validates one versioned launcher manifest.
func Load(path string) (Manifest, error) {
	file, err := os.Open(path)
	if err != nil {
		return Manifest{}, fmt.Errorf("open manifest: %w", err)
	}
	defer file.Close()

	decoder := json.NewDecoder(file)
	decoder.DisallowUnknownFields()

	var manifest Manifest
	if err := decoder.Decode(&manifest); err != nil {
		return Manifest{}, fmt.Errorf("manifest: invalid JSON")
	}
	if err := requireEOF(decoder); err != nil {
		return Manifest{}, err
	}
	if err := manifest.validate(); err != nil {
		return Manifest{}, err
	}
	return manifest, nil
}

func requireEOF(decoder *json.Decoder) error {
	var extra struct{}
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return errors.New("manifest: must contain one JSON value")
	}
	return nil
}

func (m Manifest) validate() error {
	if m.Version != version {
		return errors.New("manifest version is unsupported")
	}
	if m.Platform != "linux" && m.Platform != "darwin" {
		return errors.New("manifest field platform is invalid")
	}
	for _, field := range []struct {
		name string
		path string
	}{
		{"fenceExecutable", m.FenceExecutable},
		{"repoWolfClientDir", m.RepoWolfClientDir},
		{"basePolicy", m.BasePolicy},
		{"closurePathsFile", m.ClosurePathsFile},
		{"scratchRoot", m.ScratchRoot},
		{"agent.executable", m.Agent.Executable},
	} {
		if err := validateAbsolute(field.name, field.path); err != nil {
			return err
		}
	}
	if len(m.ACLProbe) == 0 {
		return errors.New("manifest field aclProbe is required")
	}
	if err := validateAbsolute("aclProbe", m.ACLProbe[0]); err != nil {
		return err
	}
	if err := validateArguments("aclProbe", m.ACLProbe[1:]); err != nil {
		return err
	}
	if err := validateAbsolutePaths("pathEntries", m.PathEntries, true); err != nil {
		return err
	}
	if err := validateArguments("protectedPathPatterns", m.ProtectedPathPatterns); err != nil {
		return err
	}
	if err := m.Agent.validate(); err != nil {
		return err
	}
	if err := m.Docker.validate("docker"); err != nil {
		return err
	}
	return m.Podman.validate("podman")
}

func (a Agent) validate() error {
	if !safeProgramName(a.Name) {
		return errors.New("manifest field agent.name is invalid")
	}
	if err := validateArguments("agent.mandatoryArgs", a.MandatoryArgs); err != nil {
		return err
	}
	if err := validateArguments("agent.reservedFlags", a.ReservedFlags); err != nil {
		return err
	}
	if !safeEnvironmentName(a.ConfigEnvironment) {
		return errors.New("manifest field agent.configEnvironment is invalid")
	}
	if err := validateAbsolutePaths("agent.defaultStatePaths", a.DefaultStatePaths, false); err != nil {
		return err
	}
	if a.DarwinSettings != "" {
		return validateAbsolute("agent.darwinSettings", a.DarwinSettings)
	}
	return nil
}

func (c ContainerConfig) validate(name string) error {
	if c.SocketPath != nil {
		if err := validateAbsolute(name+".socketPath", *c.SocketPath); err != nil {
			return err
		}
	}
	return validateAbsolutePaths(name+".clientPrograms", c.ClientPrograms, false)
}

func validateAbsolutePaths(field string, paths []string, required bool) error {
	if required && len(paths) == 0 {
		return fmt.Errorf("manifest field %s is required", field)
	}
	for _, path := range paths {
		if err := validateAbsolute(field, path); err != nil {
			return err
		}
	}
	return nil
}

func validateAbsolute(field, path string) error {
	if path == "" || strings.IndexByte(path, 0) >= 0 || !filepath.IsAbs(path) {
		return fmt.Errorf("manifest field %s is invalid", field)
	}
	return nil
}

func validateArguments(field string, arguments []string) error {
	for _, argument := range arguments {
		if argument == "" || strings.IndexByte(argument, 0) >= 0 {
			return fmt.Errorf("manifest field %s is invalid", field)
		}
	}
	return nil
}

func safeProgramName(name string) bool {
	if name == "" || name == "." || name == ".." {
		return false
	}
	for _, character := range name {
		if !(unicode.IsLetter(character) || unicode.IsDigit(character) || character == '.' || character == '_' || character == '-') {
			return false
		}
	}
	return true
}

func safeEnvironmentName(name string) bool {
	if name == "" {
		return false
	}
	for index, character := range name {
		if !(character == '_' || unicode.IsLetter(character) || (index > 0 && unicode.IsDigit(character))) {
			return false
		}
	}
	return true
}
